# Generated by Django 4.2.16 on 2024-09-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_account', '0003_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True, max_length=200, null=True)),
                ('work_deadline', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_per_hour', models.PositiveIntegerField()),
                ('job_image', models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeDkSNW9wtNePKrUAr1M8nbZvLO5AF8t0TMg&s', upload_to='jobImage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_account.profile')),
            ],
        ),
    ]
