# Generated by Django 4.2.16 on 2024-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='category',
            field=models.CharField(default='House', max_length=100),
        ),
    ]
