# Generated by Django 4.2.16 on 2024-09-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_job_details_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.job_details')),
            ],
        ),
    ]
