# Generated by Django 4.2.16 on 2024-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_categoryadd_alter_job_details_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='area',
            field=models.CharField(default='UK', max_length=100),
        ),
    ]
