# Generated by Django 4.2.16 on 2024-09-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_categoryadd_category_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryAdd',
            new_name='Categories',
        ),
    ]
